### ISSUE TITLE
Switch between debug and release

### ISSUE THREAD

**Issue by notdanilo** [sensorial-systems/cargo-ligen#1]
https://github.com/sensorial-systems/cargo-ligen/blob/246f7787c8612e92d565ca2866fc6721c7aca073/src/main.rs#L28

**Comment by arrudagates** [comment]
Fixed with [this commit](https://github.com/sensorial-systems/cargo-ligen/commit/51eb14013a75b96934c48e02a1864b60f9be2b90)
