### ISSUE TITLE
Support workspaces

### ISSUE THREAD

**Issue by notdanilo** [sensorial-systems/cargo-ligen#2]
`Process 1` - If the Cargo.toml is a workspace:
1. Build all members, copy all libraries from `workspace/target/<release>/<library-name>` to `workspace/target/lib`

`Process 2` - If the Cargo.toml is a member:
1. It finds the workspace Cargo.toml and starts `Process 1`.

**Comment by arrudagates** [comment]
New route:

`Process 1` - If the Cargo.toml is a workspace:

1. Find all members
2. Iterate over them, building each one individually with --target-dir pointing to the root of the workspace
2. Copy all libraries from workspace/target/<release>/<library-name> to workspace/target/ligen/<crate_name>/lib

`Process 2` - If the Cargo.toml is a member:

1. It finds the workspace Cargo.toml and starts Process 1.
